package com.memoeslink.generator.spanish;

public class Constant {
    public static final String ALPHABET = "abcdefghijklmnñopqrstuvwxyz";
    public static final String LOWERCASE_ALPHABET = "abcdefghijklmnñopqrstuvwxyz";
    public static final String UPPERCASE_ALPHABET = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ";
    public static final String LETTERS = "abcdefghijklmnñopqrstuvwxyzABCDEFGHIJKLMNÑOPQRSTUVWXYZ";
    public static final String VOWELS = "aeiouAEIOU";
    public static final String VOWELS_WITH_DIACRITIC = "áéíóúüÁÉÍÓÚÜ";
    public static final String ALL_VOWELS = "aáeéiíoóuúüAÁEÉIÍOÓUÚÜ";
    public static final String CONSONANTS = "bcdfghjklmnñpqrstvwxyzBCDFGHJKLMNÑPQRSTVWXYZ";
    public static final String CLASSES = "alquimista¶ arquero[a]¶ asesino[a]¶ bardo/trovadora¶ bárbaro[a]¶ caballero/amazona¶ cazador[a]¶ clérigo/sacerdotisa¶ curandero[a]¶ dragoon¶ druida¶ elementalista¶ escudero[a]¶ espadachín/espadachina¶ espadero[a]¶ exorcista¶ explorador[a]¶ guerrero[a]¶ hechicero[a]¶ ilusionista¶ ingeniero[a]¶ invocador[a]¶ jinete oscuro[a]¶ ladrón/ladrona¶ lancero[a]¶ mago[a]¶ mago[a] rojo[a]¶ magus¶ mercenario[a]¶ monje/peleadora¶ médico[a]¶ nigromante¶ ninja¶ oráculo¶ paladín¶ pícaro[a]¶ pirata¶ rastreador[a]¶ samurai¶ soldado¶ templario[a]¶ trasmutador[a]";
    public static final String[] ANONYMOUS_ANIMALS = {"caimán", "oso hormiguero", "armadillo", "uro", "ajolote", "tejón", "murciélago", "oso", "castor", "pez globo", "búfalo", "camello", "camaleón", "guepardo", "ardilla", "chinchilla", "chupacabras", "cormorán", "coyote", "cuervo", "dingo", "dinosaurio", "perro", "delfín", "dragón", "pato", "pulpo dumbo", "elefante", "hurón", "zorro", "rana", "jirafa", "ganso", "topo", "grizzly", "hámster", "erizo", "hipopótamo", "hiena", "chacal", "lebrílope", "íbice", "ifrit", "iguana", "canguro", "kiwi", "koala", "kraken", "lémur", "leopardo", "ligre", "león", "llama", "manatí", "visón", "mono", "alce", "narval", "Nyan Cat", "orangután", "nutria", "panda", "pingüino", "ornitorrinco", "pitón", "calabaza", "quagga", "quokka", "conejo", "mapache", "rinoceronte", "oveja", "musaraña", "mofeta", "loris lento", "ardilla", "tigre", "tortuga", "unicornio", "morsa", "lobo", "glotón", "wombat"};
    public static final String[] TITLE_DESCRIPTOR = {"Superior", "Senior", "Adjunto[a]", "Corporativo[a]", "Dinámico[a]", "Futuro[a]", "de Producto", "Nacional", "Regional", "Distrital", "Central", "Global", "del Cliente", "de Inversión", "Dinámico[a]", "Internacional", "Patrimonial", "Avanzado[a]", "Interno[a]", "Humano[a]", "Jefe[a]", "Principal"};
    public static final String[] TITLE_JOB = {"Supervisor[a]", "Asociado[a]", "Ejecutivo[a]", "Intermediario[a]", "Oficial", "Gerente", "Ingeniero[a]", "Especialista", "Director[a]", "Coordinador[a]", "Administrador[a]", "Arquitecto[a]", "Analista", "Diseñador[a]", "Planificador[a]", "Orquestador[a]", "Técnico[a]", "Desarrollador[a]", "Productor[a]", "Consultor[a]", "Asistente", "Facilitador[a]", "Agente", "Representante", "Estratega"};
    public static final String[] TITLE_LEVEL = {"Soluciones", "Programa", "Marca", "Seguridad", "Investigación", "Mercadotecnia", "Directivas", "Implementación", "Integración", "Funcionalidad", "Respuesta", "Integración", "Tácticas", "Identidad", "Mercados", "Grupo", "División", "Aplicaciones", "Optimización", "Operaciones", "Infraestructura", "Intranet", "Comunicaciones", "Web", "Marca", "Calidad", "Aseguramiento", "Movilidad", "Cuentas", "Integración", "Creatividad", "Configuración", "Rendición de Cuentas", "Interacciones", "Factores", "Usabilidad", "Métricas", "Atención", "Sistemas"};
    public static final String[] HONORIFICS = {"[Sr[,a]].", "[Srit[o,a]].", "D.[[,ª]]", "[Sr[,a]].", "[Dr[,a]].", "[Prof[,a]].", "[Lcd[o,a]].", "Ing.", "Dir.[[,ª]]", "[Pdt[e,a]]."};
    public static final String[] ROYAL_TITLES = {"[^bar[ón,onesa]]", "[^conde[,sa]]", "[^duque[,sa]]", "[^empera[dor,triz]]", "[^k[áiser,aiserin]]", "[^marqu[és,esa]]", "[^pap[a,isa]]", "[^pr[íncipe,incesa]]", "[^re[y,ina]]", "[^vizconde[,sa]]", "[^zar[,ina]]", "[^r[ex,ēgīna]]", "[^sult[án,ana]]"};
}
