package com.memoeslink.generator.english;

public class Constant {
    public static final String ALPHABET = "abcdefghijklmnopqrstuvwxyz";
    public static final String LOWERCASE_ALPHABET = "abcdefghijklmnopqrstuvwxyz";
    public static final String UPPERCASE_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    public static final String LETTERS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    public static final String VOWELS = "aeiouAEIOU";
    public static final String LOWERCASE_VOWELS = "aeiou";
    public static final String UPPERCASE_VOWELS = "AEIOU";
    public static final String CONSONANTS = "bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ";
    public static final String LOWERCASE_CONSONANTS = "bcdfghjklmnpqrstvwxyz";
    public static final String UPPERCASE_CONSONANTS = "BCDFGHJKLMNPQRSTVWXYZ";
    public static final String CLASSES = "alchemist¶ archer¶ assassin¶ bard¶ barbarian¶ knight/knightess¶ hunter¶ cleric¶ healer¶ dragoon¶ druid¶ elementalist¶ squire¶ swordsman¶ swordsmith¶ exorcist¶ scout¶ warrior¶ sorcerer¶ illusionist¶ engineer¶ summoner¶ dark rider¶ thief¶ spearman¶ mage¶ red mage¶ magus¶ mercenary¶ monk¶ doctor¶ necromancer¶ ninja¶ oracle¶ paladin¶ rogue¶ pirate¶ tracker¶ samurai¶ soldier¶ templar¶ transmuter";
    public static final String[] ANONYMOUS_ANIMALS = {"alligator", "anteater", "armadillo", "auroch", "axolotl", "badger", "bat", "bear", "beaver", "blobfish", "buffalo", "camel", "chameleon", "cheetah", "chipmunk", "chinchilla", "chupacabra", "cormorant", "coyote", "crow", "dingo", "dinosaur", "dog", "dolphin", "dragon", "duck", "dumbo octopus", "elephant", "ferret", "fox", "frog", "giraffe", "goose", "gopher", "grizzly", "hamster", "hedgehog", "hippo", "hyena", "jackal", "jackalope", "ibex", "ifrit", "iguana", "kangaroo", "kiwi", "koala", "kraken", "lemur", "leopard", "liger", "lion", "llama", "manatee", "mink", "monkey", "moose", "narwhal", "nyan cat", "orangutan", "otter", "panda", "penguin", "platypus", "python", "pumpkin", "quagga", "quokka", "rabbit", "raccoon", "rhino", "sheep", "shrew", "skunk", "slow loris", "squirrel", "tiger", "turtle", "unicorn", "walrus", "wolf", "wolverine", "wombat"};
    public static final String[] GENERATIONAL_SUFFIX = {"Jr.", "Sr."};
    public static final String[] TITLE_DEPARTMENT = {"Accounting", "Administration", "Business Development", "Compliance", "Customer Service", "Data Analysis", "Finance", "Human Resources", "Information Technology", "Legal", "Marketing", "Operations", "Procurement", "Production", "Project Management", "Public Relations", "Quality Assurance", "Research and Development", "Sales", "Supply Chain", "Technical Support", "Training and Development", "Logistics", "Health and Safety", "Product Management", "Strategic Planning", "Communications", "Facilities Management", "Risk Management", "Corporate Social Responsibility"};
    public static final String[] TITLE_DESCRIPTOR = {"Lead", "Senior", "Direct", "Corporate", "Dynamic", "Future", "Product", "National", "Regional", "District", "Central", "Global", "Customer", "Investor", "Dynamic", "International", "Legacy", "Forward", "Internal", "Human", "Chief", "Principal", "Contractual"};
    public static final String[] TITLE_JOB = {"Supervisor", "Associate", "Executive", "Liaison", "Officer", "Manager", "Engineer", "Specialist", "Director", "Coordinator", "Administrator", "Architect", "Analyst", "Designer", "Planner", "Orchestrator", "Technician", "Developer", "Producer", "Consultant", "Assistant", "Facilitator", "Agent", "Representative", "Strategist", "Editor", "Trainer", "Partner", "Recruiter", "Clerk"};
    public static final String[] TITLE_LEVEL = {"Solutions", "Program", "Brand", "Security", "Research", "Marketing", "Directives", "Implementation", "Integration", "Functionality", "Response", "Paradigm", "Tactics", "Identity", "Markets", "Group", "Division", "Applications", "Optimization", "Operations", "Infrastructure", "Intranet", "Communications", "Web", "Branding", "Quality", "Assurance", "Mobility", "Accounts", "Data", "Creative", "Configuration", "Accountability", "Interactions", "Factors", "Usability", "Metrics", "Support", "System"};
    public static final String[] HONORIFICS = {"[Mr[,s]].", "[[Master,Miss]]", "[[Sir,Dame]]", "[[Lord,Lady]]", "Dr.", "Prof.", "Gr.", "Eng.", "Dir.", "Pres."};
    public static final String[] ROYAL_TITLES = {"[Baron[,ess]]", "[Count[,ess]]", "[Du[ke,chess]]", "[Emp[eror,ress]]", "[Kaiser[,in]]", "[Mar[quess,chioness]]", "Pope", "[Prince[,ss]]", "[[King,Queen]]", "[Viscount[,ess]]", "[Tsar[,ina]]", "[R[ex,ēgīna]]", "[Sultan[,a]]"};
    public static final String[] RELATIONSHIP = {"a person", "an unknown person", "a related person to %s", "the couple of %s", "the spouse of %s", "the concubine of %s", "the best friend of %s", "the worst enemy of %s", "the closest person to %s", "someone who offers a service to %s", "someone who sells anything to %s", "someone close to %s", "a lover of %s", "a relative of %s", "a distant relative of %s", "a colleague of %s", "a friend of %s", "an enemy of %s", "a good friend of %s", "a comrade of %s", "a fellow of %s", "a companion of %s", "a teammate of %s", "a coworker of %s", "a classmate of %s", "a roommate of %s", "a business associate of %s", "a customer of %s", "a prospect of %s", "an acquaintance of %s", "a neighbor of %s", "a follower of %s", "an observer of %s", "an ally of %s", "a rival of %s", "an apprentice of %s", "a mentor of %s"};
    public static final String[] UNSPECIFIC_RELATIONSHIP = {"a friend", "a foe", "a relative", "a distant relative", "an acquaintance", "a neighbor", "an unknown person", "a fellow", "a comrade", "a companion", "a lover", "a follower", "a work-related person", "an associate", "a partner", "a third party", "a random person"};
}
