package com.memoeslink.generator.international;

public final class Constant {
    public static final String ADMIN_USERNAME_EXPERTISE = "Cloud¶ Network¶ Data¶ Cyber¶ Security¶ Server¶ System¶ Code¶ IT¶ Tech¶ Script¶ Firewall¶ Root¶ Virtual¶ Hardware¶ Mobile¶ Web¶ BigData¶ AI¶ Blockchain¶ DevOps¶ IoT¶ CloudOps¶ Microservices¶ Analytics¶ MachineLearning¶ Automation¶ Quantum¶ API¶ Docker¶ Kubernetes¶ Database¶ UX¶ UI¶ VPN¶ CDN¶ CDN¶ CDN¶ Agile¶ Scrum¶ Git¶ Jenkins¶ Maven¶ Ansible¶ Puppet¶ Chef¶ Terraform¶ Selenium¶ Jira¶ Splunk¶ Elastic¶ Kibana¶ Grafana¶ Prometheus¶ Nagios¶ Wireshark¶ Apache¶ Nginx¶ MySQL¶ PostgreSQL¶ MongoDB¶ Redis¶ Elasticsearch¶ Cassandra¶ Hadoop¶ Spark¶ Kafka¶ RabbitMQ¶ Spring¶ React¶ Angular¶ Vue¶ Node¶ Express¶ Django¶ Flask¶ Laravel¶ Symfony¶ ASP.NET¶ RubyonRails¶ Go¶ Rust¶ Swift¶ Kotlin¶ TypeScript¶ JavaScript¶ Python¶ Java¶ CSharp¶ Cplusplus¶ HTML¶ CSS¶ PHP¶ Shell¶ PowerShell¶ Bash¶ JSON¶ XML¶ YAML¶ SQL";
    public static final String ADMIN_USERNAME_TITLE = "Power¶ System¶ Admin¶ Master¶ Nexus¶ Sentinel¶ Guardian¶ Oracle¶ Cipher¶ Vortex¶ Luminary¶ Nova¶ Quantum¶ Phoenix¶ Vertex¶ Catalyst¶ Specter¶ Horizon¶ Synapse¶ Aeon¶ Infinity¶ Equinox¶ Matrix¶ Axiom¶ Allegiance¶ Chronos¶ Arcturus¶ Polaris¶ Zenith¶ Enigma¶ Odyssey¶ Zen¶ Echo¶ Icon¶ Byte¶ Solstice¶ Spectrum¶ Astral¶ Zephyr¶ Draco¶ Neptune¶ Comet¶ Cypher¶ Falcon¶ Meteor¶ Genesis¶ Auror¶ Lyra¶ Argus¶ Omen¶ Eon¶ Spark¶ Nebula¶ Pulsar¶ Orion¶ Celest¶ Binary¶ Artemis¶ Seraph¶ Chrono¶ Sirius¶ Helix¶ Ion¶ Apex¶ Nimbus¶ Paragon¶ Quasar¶ Synth¶ Titan¶ Stellar¶ Eclipse¶ Aegis¶ Hyper¶ Atlas¶ Helios¶ Sphynx¶ Tesseract¶ Valiant¶ Astra¶ Aether¶ Lyric¶ Ursa¶ Celestial¶ Electra¶ Kinesis¶ Quanta¶ Photon¶ Nemesis¶ Pulse¶ Aura¶ Allegro¶ Chimera¶ Serene¶ Argos¶ Ignis¶ Luna¶ Aquila¶ Volta¶ Lux¶ Scepter¶ Anchor¶ Archer¶ Artist¶ Atom¶ Aviator¶ Baker¶ Breeze¶ Cactus¶ Captain¶ Carver¶ Charger¶ Chaser¶ Chime¶ Citizen¶ Climber¶ Conductor¶ Cosmo¶ Creator¶ Cruiser¶ Curator¶ Cyclone¶ Dancer¶ Defender¶ Delta¶ Dreamer¶ Drifter¶ Engineer¶ Enforcer¶ Flare¶ Fluke¶ Forecaster¶ Frontier¶ Galax¶ Gamer¶ Gatherer¶ Guide¶ Harbor¶ Harbinger¶ Haven¶ Hero¶ Hunter¶ Impact¶ Innovator¶ Intruder¶ Inventor¶ Jet¶ Juggernaut¶ Keeper¶ Knight¶ Lantern¶ Legend¶ Liberty¶ Lunar¶ Maverick¶ Mentor¶ Messenger¶ Mirage¶ Navigator¶ Nomad¶ Outlaw¶ Paladin¶ Pathfinder¶ Patron¶ Pioneer¶ Pixel¶ Poet¶ Polar¶ Prism¶ Protector¶ Prowler¶ Quest¶ Ranger¶ Raven¶ Rebel¶ Recluse¶ Remnant¶ Riddle¶ Rogue¶ Ruler¶ Scribe¶ Seeker¶ Serenade¶ Shade¶ Shadow¶ Shaman¶ Shifter¶ Skylark¶ Starling¶ Stargazer¶ Storm¶ Striker¶ Summoner¶ Swirl¶ Swift¶ Symphony¶ Tamer¶ Templar¶ Tide¶ Trailblazer¶ Trickster¶ Twilight¶ Typhoon¶ Vanguard¶ Venture¶ Voyager¶ Wanderer¶ Weaver¶ Whisper¶ Wizard¶ Wraith¶ Xeno¶ Overseer¶ Steward¶ Warden¶ Custodian¶ Manager¶ Controller¶ Director¶ Supervisor¶ Operator¶ Organizer¶ Moderator¶ Inspector¶ Arbiter¶ Executor¶ Regulator¶ Caretaker¶ Mediator¶ Advocate¶ Facilitator¶ Ombudsman¶ Governor¶ Peacekeeper¶ Referee¶ Designer¶ Coordinator¶ Surveyor¶ Administrator¶ Authority¶ Watcher¶ Consultant¶ Planner¶ Technician¶ Ninja¶ Guru¶ Commander¶ Champion¶ Conqueror¶ King¶ Emperor¶ Prince¶ Sorcerer¶ Enchanter¶ Whisperer¶ Prophet¶ Visionary¶ Virtuoso¶ Maestro¶ Genius¶ Architect¶ Magician¶ Siren¶ Reaper¶ Vigilant¶ Avenger¶ Crusader¶ Explorer¶ Traveler¶ Adventurer¶ Disciple¶ Scholar¶ Wrangler¶ Strategist¶ Artisan¶ Alchemist¶ Analyst¶ Developer¶ Programmer¶ Coder¶ Scripter¶ Hacker¶ Debugger¶ Tester¶ Leader¶ Pilot¶ Magus¶ Conjurer¶ Thaumaturge¶ Prodigy¶ Journeyman¶ Adept¶ Principal¶ Executive¶ Ambassador¶ Connoisseur";
    public static final String ADMIN_USERNAMES = "admin¶ root¶ guest¶ user¶ administrator¶ system¶ sys¶ test¶ operator¶ demo¶ nobody¶ service¶ local¶ superuser¶ manager¶ public¶ default¶ sysadmin¶ sqladmin¶ network¶ daemon¶ bin¶ sync¶ shutdown¶ halt¶ mail¶ news¶ uucp¶ operator¶ games¶ gopher¶ ftp¶ man¶ lp¶ irc¶ gnats¶ postgres¶ pop¶ exim¶ mailman¶ mysql¶ www-data¶ backup¶ sshd¶ bind¶ dhcp¶ cyrus¶ dovecot¶ messagebus¶ avahi¶ polkitd¶ abrt¶ dbus¶ ntp¶ rtkit¶ chrony¶ unbound¶ tss¶ nm-openconnect¶ geoclue¶ colord¶ git¶ nm-openvpn¶ plex¶ redis¶ mongodb¶ apache¶ nginx¶ nobody¶ webalizer¶ pi¶ ftpuser¶ tomcat¶ jboss¶ saslauth¶ pulse¶ avahi-autoipd¶ radvd¶ proxy¶ usbmux¶ rtkit¶ lightdm¶ whoopsie¶ speech-dispatcher¶ kernoops¶ hplip¶ saned¶ hdfs¶ yarn¶ hadoop¶ mapred¶ zookeeper¶ jenkins¶ syslog¶ nscd¶ smmsp¶ postgres¶ dovenull¶ sshd¶ postfix¶ cups¶ avahi¶ gdm¶ clamav¶ messagebus¶ haldaemon¶ ftp¶ named¶ wwwrun¶ bin¶ daemon¶ adm¶ lp¶ sync¶ shutdown¶ halt¶ mail¶ news¶ uucp¶ proxy¶ Majordom¶ postgres¶ www-data¶ backup¶ list¶ irc¶ gnats¶ nobody¶ systemd-bus-proxy¶ systemd-network¶ systemd-resolve¶ systemd-timesync¶ uuidd¶ tcpdump¶ landscape¶ pollinate¶ puppet¶ chef¶ docker¶ consul¶ salt¶ ansible¶ kubernetes¶ rabbitmq¶ sensu¶ logstash¶ influxdb¶ telegraf¶ neo4j¶ prometheus¶ grafana¶ elasticsearch¶ kibana¶ beats¶ suricata¶ pfsense¶ openvpn¶ ipsec¶ strongswan¶ wireguard¶ freeradius¶ snort¶ zeek¶ squid¶ samba¶ cifs¶ nfs¶ iscsi¶ gluster¶ ceph¶ sssd¶ ldap¶ kerberos¶ sssd¶ nslcd¶ winbind¶ htcacheclean¶ dovecot¶ aegir¶ amavis¶ Debian-exim¶ dnsmasq¶ fetchmail¶ ftpd¶ mldonkey¶ mumble-server¶ pure-ftpd¶ openldap¶ ntp¶ redis¶ rtkit¶ sddm¶ spamd¶ uucp¶ xrdp¶ zabbix¶ tor¶ snmp¶ cpanel¶ whm";

    private Constant() {
    }
}
