package com.memoeslink.generator.spanish.mexico;

public final class Constant {
    public static final String[] FEMALE_FORENAMES = {
            "Abigail",
            "Abril",
            "Adriana",
            "Agustina",
            "Aitana",
            "Alba",
            "Alejandra",
            "Alexa",
            "Alexandra",
            "Alicia",
            "Allison",
            "Alondra",
            "Amanda",
            "Ana",
            "Ana Maria",
            "Ana María",
            "Ana Sofía",
            "Ana Victoria",
            "Andrea",
            "Ángela",
            "Angélica",
            "Antonella",
            "Antonia",
            "Ariana",
            "Ashley",
            "Aurora",
            "Bárbara",
            "Bianca",
            "Briana",
            "Camila",
            "Candela",
            "Carla",
            "Carmen",
            "Carolina",
            "Catalina",
            "Cecilia",
            "Celia",
            "Clara",
            "Claudia",
            "Concepción",
            "Constanza",
            "Cristina",
            "Daniela",
            "Delfina",
            "Diana",
            "Dolores",
            "Dulce María",
            "Elena",
            "Elizabeth",
            "Emilia",
            "Emily",
            "Emma",
            "Esmeralda",
            "Esperanza",
            "Estefanía",
            "Esther",
            "Evelyn",
            "Fátima",
            "Fernanda",
            "Florencia",
            "Francisca",
            "Gabriela",
            "Génesis",
            "Gloria",
            "Graciela",
            "Guadalupe",
            "Irma",
            "Isabel",
            "Isabella",
            "Isidora",
            "Jazmín",
            "Jennifer",
            "Jimena",
            "Josefina",
            "Juana",
            "Juanita",
            "Julia",
            "Juliana",
            "Julieta",
            "Kimberly",
            "Laura",
            "Laura Sofía",
            "Leticia",
            "Lola",
            "Lucía",
            "Luciana",
            "Luna",
            "Luz María",
            "Manuela",
            "Margarita",
            "María",
            "María Camila",
            "María de Jesús",
            "María de la Luz",
            "María de los Ángeles",
            "María del Carmen",
            "María del Rosario",
            "María Elena",
            "María Fernanda",
            "María Guadalupe",
            "María Isabel",
            "María José",
            "María Luisa",
            "María Teresa",
            "Mariana",
            "Marisol",
            "Marta",
            "Martha",
            "Martina",
            "Melanie",
            "Melissa",
            "Mía",
            "Micaela",
            "Michelle",
            "Miranda",
            "Monserrat",
            "Morena",
            "Naomí",
            "Natalia",
            "Natalie",
            "Nicole",
            "Paloma",
            "Paola",
            "Patricia",
            "Paula",
            "Paulin",
            "Paulina",
            "Petra",
            "Pilar",
            "Raquel",
            "Rebeca",
            "Regina",
            "Renata",
            "Romina",
            "Rosa",
            "Rosa María",
            "Sabrina",
            "Samantha",
            "Sara",
            "Silvia",
            "Sofia",
            "Sofía",
            "Stephanie",
            "Susana",
            "Teresa",
            "Valentina",
            "Valeria",
            "Valerie",
            "Vanessa",
            "Verónica",
            "Victoria",
            "Virginia",
            "Ximena",
            "Yamileth",
            "Yolanda",
            "Zoe"
    };
    public static final String[] MALE_FORENAMES = {
            "Aarón",
            "Abraham",
            "Adrián",
            "Agustín",
            "Alan",
            "Alberto",
            "Alejandro",
            "Alexander",
            "Alexis",
            "Alfonso",
            "Alfredo",
            "Álvaro",
            "Andrés",
            "Ángel",
            "Ángel Gabriel",
            "Anthony",
            "Antonio",
            "Armando",
            "Arturo",
            "Axel",
            "Bautista",
            "Benjamín",
            "Brayan",
            "Bruno",
            "Carlos",
            "César",
            "Christopher",
            "Cristian",
            "Cristóbal",
            "Daniel",
            "David",
            "Diego",
            "Diego Alejandro",
            "Dylan",
            "Eduardo",
            "Elias",
            "Emiliano",
            "Emilio",
            "Emmanuel",
            "Enrique",
            "Erick",
            "Ernesto",
            "Esteban",
            "Facundo",
            "Felipe",
            "Fernando",
            "Francisco",
            "Francisco Javier",
            "Franco",
            "Gabriel",
            "Gael",
            "Gerardo",
            "Gonzalo",
            "Guillermo",
            "Gustavo",
            "Héctor",
            "Hugo",
            "Ian",
            "Ignacio",
            "Iker",
            "Isaac",
            "Ismael",
            "Israel",
            "Iván",
            "Javier",
            "Jerónimo",
            "Jesús",
            "Joaquín",
            "Jonathan",
            "Jorge",
            "José",
            "José Ángel",
            "José Antonio",
            "José de Jesús",
            "José Guadalupe",
            "José Luis",
            "José Manuel",
            "José Miguel",
            "Joshua",
            "Josué",
            "Juan",
            "Juan Andrés",
            "Juan Carlos",
            "Juan David",
            "Juan José",
            "Juan Manuel",
            "Juan Pablo",
            "Juan Sebastián",
            "Julián",
            "Julio César",
            "Kevin",
            "Leonardo",
            "Leonel",
            "Luca",
            "Lucas",
            "Luciano",
            "Luis",
            "Luis Ángel",
            "Luis Fernando",
            "Manuel",
            "Marco Antonio",
            "Marcos",
            "Mario",
            "Martín",
            "Mateo",
            "Matías",
            "Mauricio",
            "Maximiliano",
            "Miguel",
            "Miguel Ángel",
            "Nicolás",
            "Oscar",
            "Pablo",
            "Patricio",
            "Pedro",
            "Rafael",
            "Ramón",
            "Raúl",
            "Ricardo",
            "Roberto",
            "Rodrigo",
            "Rubén",
            "Salvador",
            "Samuel",
            "Santiago",
            "Santino",
            "Sebastián",
            "Sergio",
            "Simón",
            "Thiago",
            "Tomás",
            "Valentín",
            "Valentino",
            "Vicente",
            "Víctor"
    };
    public static final String[] SURNAMES = {
            "Acosta",
            "Aguilar",
            "Aguirre",
            "Alonso",
            "Alvarado",
            "Álvarez",
            "Andrade",
            "Arellano",
            "Arias",
            "Arroyo",
            "Ávila",
            "Ayala",
            "Barajas",
            "Barrera",
            "Bautista",
            "Becerra",
            "Beltrán",
            "Benítez",
            "Bernal",
            "Bravo",
            "Caballero",
            "Cabrera",
            "Calderón",
            "Camacho",
            "Campos",
            "Cano",
            "Cantú",
            "Cárdenas",
            "Carmona",
            "Carrillo",
            "Castañeda",
            "Castellanos",
            "Castillo",
            "Castro",
            "Cervantes",
            "Chávez",
            "Cisneros",
            "Contreras",
            "Córdova",
            "Corona",
            "Cortes",
            "Cruz",
            "Cuevas",
            "Dávila",
            "de la Cruz",
            "de la Rosa",
            "Delgado",
            "Díaz",
            "Domínguez",
            "Duran",
            "Enríquez",
            "Escobar",
            "Esparza",
            "Espinosa",
            "Espinoza",
            "Esquivel",
            "Estrada",
            "Fernández",
            "Figueroa",
            "Flores",
            "Franco",
            "Fuentes",
            "Galindo",
            "Gallardo",
            "Gallegos",
            "Galván",
            "García",
            "Garza",
            "Gómez",
            "Gonzales",
            "González",
            "Guerra",
            "Guerrero",
            "Guevara",
            "Gutiérrez",
            "Guzmán",
            "Hernández",
            "Hernández",
            "Herrera",
            "Huerta",
            "Ibarra",
            "Islas",
            "Jarca",
            "Jiménez",
            "Juárez",
            "Lara",
            "Leal",
            "León",
            "Leyva",
            "López",
            "Lozano",
            "Lugo",
            "Luna",
            "Macías",
            "Maldonado",
            "Marín",
            "Márquez",
            "Martínez",
            "Martínez",
            "Mata",
            "Medina",
            "Mejía",
            "Méndez",
            "Mendoza",
            "Mercado",
            "Meza",
            "Miranda",
            "Molina",
            "Monroy",
            "Montes",
            "Montiel",
            "Montoya",
            "Mora",
            "Morales",
            "Moreno",
            "Muñoz",
            "Nava",
            "Navarrete",
            "Navarro",
            "Núñez",
            "Ochoa",
            "Olivares",
            "Olvera",
            "Orozco",
            "Ortega",
            "Ortiz",
            "Osorio",
            "Pacheco",
            "Padilla",
            "Palacios",
            "Paredes",
            "Parra",
            "Pena",
            "Peralta",
            "Pérez",
            "Pineda",
            "Ponce",
            "Quintero",
            "Quiroz",
            "Ramírez",
            "Ramos",
            "Rangel",
            "Reyes",
            "Reyna",
            "Ríos",
            "Rivas",
            "Rivera",
            "Robles",
            "Rocha",
            "Rodríguez",
            "Rodríguez",
            "Rojas",
            "Romero",
            "Romo",
            "Rosales",
            "Rosas",
            "Rubio",
            "Ruiz",
            "Salas",
            "Salazar",
            "Salgado",
            "Salinas",
            "Sánchez",
            "Sánchez",
            "Sandoval",
            "Santiago",
            "Santos",
            "Serrano",
            "Silva",
            "Solís",
            "Sosa",
            "Soto",
            "Suarez",
            "Tapia",
            "Téllez",
            "Torres",
            "Tovar",
            "Trejo",
            "Trujillo",
            "Uribe",
            "Valdés",
            "Valdez",
            "Valencia",
            "Valenzuela",
            "Vargas",
            "Vázquez",
            "Vega",
            "Velasco",
            "Velázquez",
            "Vera",
            "Villa",
            "Villalobos",
            "Villanueva",
            "Villarreal",
            "Villegas",
            "Zamora",
            "Zarate",
            "Zavala",
            "Zepeda",
            "Zúñiga"
    };

    private Constant() {
    }
}